"""Add community field to Scenario model

Revision ID: b2ec67e6fc85
Revises: 6d699ae1f065
Create Date: 2024-07-17 00:30:37.114098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ec67e6fc85'
down_revision = '6d699ae1f065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.drop_column('community')

    # ### end Alembic commands ###
